name: Continuous Deployment

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publishing for ${{ matrix.job.os }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        rust: [stable]
        job:
          - os: macos-latest
            artifact_prefix: macos
            target: x86_64-apple-darwin
            binary_postfix: ""
          - os: ubuntu-latest
            artifact_prefix: linux
            target: x86_64-unknown-linux-gnu
            binary_postfix: ""
          - os: windows-latest
            artifact_prefix: windows
            target: x86_64-pc-windows-msvc
            binary_postfix: ".exe"

    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: ${{ matrix.rust }}
          args: --release --target ${{ matrix.job.target }}

      - name: Packaging final binary
        shell: bash
        run: |
          cd target/${{ matrix.job.target }}/release
          strip rust-gh-example${{ matrix.job.binary_postfix }}
          tar czvf rust-gh-example-${{ matrix.job.artifact_prefix }}.tar.gz rust-gh-example${{ matrix.job.binary_postfix }}

          if [[ ${{ runner.os }} == 'Windows' ]]; then
            certutil -hashfile rust-gh-example-${{ matrix.job.artifact_prefix }}.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > rust-gh-example-${{ matrix.job.artifact_prefix }}.sha256
          else
            shasum -a 256 rust-gh-example-${{ matrix.job.artifact_prefix }}.tar.gz > rust-gh-example-${{ matrix.job.artifact_prefix }}.sha256
          fi
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.job.target }}/release/rust-gh-example-${{ matrix.job.artifact_prefix }}.tar.gz
            target/${{ matrix.job.target }}/release/rust-gh-example-${{ matrix.job.artifact_prefix }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
